import Head from 'next/head';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillInstagram } from 'react-icons/ai';
import { MdDarkMode } from 'react-icons/md'
import { useState } from 'react';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Poda Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
      </Head>

      <main className="font-poppins bg-white px-5 md:px-10 lg:px-40 dark:bg-gray-900">
        <section className="">

          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">podatech</h1>
            <ul className="flex items-center">
              <li><a href="#" className="px-4  rounded-md ml-8 dark:text-white">SkillShare</a></li>
              <li><a href="#" className="px-4  rounded-md dark:text-white">UniPubs</a></li>
              <li><a href="#" className="flex bg-cyan-500 text-white px-4 rounded-md ml-4 mr-4"><span>Blog</span></a></li>
              <li><MdDarkMode onClick={() => { setDarkMode('darkMode') }} className="hidden md:block cursor-pointer text-2xl text-darkBlue dark:text-cyan-500 ml-4" /></li>
            </ul>
          </nav>

          <div className="flex justify-center">
            <div>  
              <div className="text-center p-10">
                <h2 className="text-5xl py-2 text-transparent bg-clip-text font-medium bg-gradient-to-r from-cyan-500 to-cyan-500">Population Data</h2>
                <h3 className="text-2xl py-2 dark:text-white">Data Visualization, Machine Learning and more...</h3>
                <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-300">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
              </div>
              <div className="text-5xl flex justify-center gap-4 md:gap-16 text-gray-700 dark:text-gray-300">
                <AiFillTwitterCircle />
                <AiFillInstagram />
                <AiFillLinkedin />
                <AiFillYoutube />
              </div>
            </div>

            {/* ANIMATION */}

            <div className="items-center hidden xl:flex">
              <div className="flex gap-2">
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake1 relative flex justify-center items-center'>
                  <h1 className="text-white">0</h1>
                </div>
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake2 relative flex justify-center items-center'>
                  <h1 className="text-white">1</h1>
                </div>
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake1 relative flex justify-center items-center'>
                  <h1 className="text-white">0</h1>
                </div>
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake2 relative flex justify-center items-center'>
                  <h1 className="text-white">1</h1>
                </div>
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake1 relative flex justify-center items-center'>
                  <h1 className="text-white">0</h1>
                </div>
                <div className='w-20 h-10 bg-cyan-500 rounded-md animate-shake2 relative flex justify-center items-center'>
                  <h1 className="text-white">1</h1>
                </div>
              </div>
            </div>
          </div>

        </section>

        <section className="h-full py-14 flex justify-center">

          <div className="py-14 px-14 h-full w-full">
            <div>
              <div className="text-3xl md:text-4xl font-semibold dark:text-white">
                <h1>Frequently asked questions</h1>
              </div>
              <div className="mt-4 dark:text-gray-300">
                <p>If you can’t find what you’re looking for, email our support team and if you’re lucky someone will get back to you.</p>
              </div>
            </div>
            <div className="flex flex-col md:flex-row gap-4">
              <div className="mt-14 dark:text-white">
                <div>
                  <div className="font-semibold">
                    <h3>Does TaxPal handle VAT?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>Well no, but if you move your company offshore you can probably ignore it.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>Can I pay for my subscription via purchase order?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>Absolutely, we are happy to take your money in all forms.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>How do I apply for a job at TaxPal?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>We only hire our customers, so subscribe for a minimum of 6 months and then let’s talk.</p>
                  </div>
                </div>
              </div>

              <div className="mt-14 dark:text-white">
                <div>
                  <div className="font-semibold">
                    <h3>What was that testimonial about tax fraud all about?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>TaxPal is just a software application, ultimately your books are your responsibility.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>TaxPal sounds horrible but why do I still feel compelled to purchase?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>This is the power of excellent visual design. You just can’t resist it, no matter how poorly it actually functions.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>I found other companies called TaxPal, are you sure you can use this name?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>Honestly not sure at all. We haven’t actually incorporated or anything, we just thought it sounded cool and made this website.</p>
                  </div>
                </div>
              </div>

              <div className="mt-14 dark:text-white">
                <div>
                  <div className="font-semibold">
                    <h3>How do you generate reports?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>You just tell us what data you need a report for, and we get our kids to create beautiful charts for you using only the finest crayons.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>Can we expect more inventory features?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>Absolutely, we are happy to take your money in all forms.</p>
                  </div>
                </div>
                <div>
                  <div className="mt-8 font-semibold">
                    <h3>I lost my password, how do I get into my account?</h3>
                  </div>
                  <div className="mt-4 dark:text-gray-300">
                    <p>Send us an email and we will send you a copy of our latest password spreadsheet so you can find your information.</p>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </section>
      </main>

    </div>
  )
}

